config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    devise_scope :user do
      authenticated :user do
        root :to => 'home#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'devise/registrations#new', as: :unauthenticated_root
      end
    resources :home, only: [:index]
    resources :weathers
    resources :places do
      resources :routes

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :routes
  belongs_to :user
  validates :name, :presence => true
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :place

  validates :grade, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :places
end

app/models/weather.rb
class Weather < ActiveRecord::Base


  before_create :current_weather

  private

  def current_weather
    begin
      response = RestClient::Request.new(
      :method => :post,
      :url => 'http://api.wunderground.com/api/febfd3b059934ab2/conditions/q/' + zip + '.json',
      :user => ENV['API_KEY'],
      :payload => { :zip => zip }
      ).execute
    # self.update, parsed response etc.

      parsed_response = JSON.parse(response)

      location_data = parsed_response['current_observation']
      self.city = location_data['display_location']['city']
      self.state = location_data['display_location']['state']
      self.forcast = location_data['temperature_string']


    rescue
      throw(:abort)
    end
  end
end

app/models/weather_condition.rb
class WeatherConditions < ActiveRecord::Base

  private

  def current_weather
    begin
      response = RestClient::Request.new(
      :method => :post,
      :url => 'http://api.wunderground.com/api/febfd3b059934ab2/conditions/q/' + zip + '.json',
      :user => ENV['API_KEY'],
      :payload => { :zip => zip}
      ).execute
    rescue
      throw(:abort)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_filer :authenticate_user!
end

# class AuthenticationController < ApplicationController
#   # Turn off user authentication for all actions in this controller
#   # skip_before_filer :authenticate_user!
#
#   def login
#     '...'
#   end
#
#   def register
#     '...'
#   end
# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
    render :index
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @user = User.find(current_user.id)
    @place = @user.places.new(place_params)
    if @place.save
      flash[:notice] = "Place successfully added!"
      redirect_to :back
    else
      flash[:alert] = "Something went wrong"
      render :back
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @user = User.find(current_user)
    @place = Place.find(params[:id])
    if @place.update(place_params)
      flash[:notice] = "Place successfully updated!"
      redirect_to :back
    else
      flash[:alert] = "Something went wrong"
      render :back
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    flash[:notice] = "Place successfully removed!"
    redirect_to places_path
  end

  private
  def place_params
    params.require(:place).permit(:name, :street_address, :city, :state, :user_id)
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @place = Place.find(params[:place_id])
    @route = @place.routes.new
  end

  def edit
  end

  def create
    @place = Place.find(params[:place_id])
    @route = @place.routes.new(route_params)
    if @route.save
      flash[:notice] = "Route saved successfully!"
      redirect_to :back
    else
      flash[:alert] = "Something went wrong"
      render :back
    end
  end

  def update
    @place = Place.find(params[:place_id])
    @route = Route.find(params[:id])
    if @route.update(route_params)
      flash[:notice] = "Update saved successfully"
      redirect_to :back
    else
      flash[:alert] = "Something went wrong"
      render :back
    end
  end

  def destroy
    @route = Route.find(params[:id])
    @place = @route.place
    if @route.destroy
      flash[:notice] = 'Route was successfully destroyed.'
      redirect_to place_path(@place)
    end
  end

  private
    def set_route
      @route = Route.find(params[:id])
      @place = @route.place
    end

    def route_params
      params.require(:route).permit( :kind, :grade, :place_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show
    @user = User.find(current_user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :current_password, :password_confirmation)
  end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  def index
    @weathers = Weather.all
  end

  def new
    @weather = Weather.new
  end

  def create
    @weather = Weather.new(weather_params)

    if @weather.save
      redirect_to weathers_path
    else
      render 'new'
    end
  end

  def show
    @weather = Weather.find(params[:id])
  end

  private

    def weather_params
      params.require(:weather).permit(:zip)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  # before_action :authenticate_user!
end

app/views/home/index.html.erb
<h1>Welcome to Rock Jock!</h1>

<p>Rock Jock is the ultimate tracker for climbers that captures both places you've climbed and the difficulty of routes you climbed at those places.</p>

<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis risus elit, hendrerit a est vitae, dignissim tempus sapien. Sed non dapibus dolor, eget lacinia nisl. Proin a suscipit purus. Nulla pulvinar purus quis lacus sollicitudin, et dictum urna maximus. Sed eleifend nibh urna, at dictum massa interdum id. Proin at eros in enim tincidunt porttitor. Etiam et massa cursus, semper magna ac, efficitur augue. Mauris non consectetur est. Vivamus tristique ligula eu ligula pulvinar volutpat. In ut est vitae leo volutpat laoreet nec sit amet neque. Quisque magna augue, dignissim et nulla eu, egestas semper nulla. Maecenas convallis ipsum in posuere varius. Maecenas blandit, justo vel ultricies tincidunt, elit elit sollicitudin dui, ut laoreet felis turpis a orci.</p>

app/views/homes/index.html.erb
<h1>Hello World</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RockJock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <p class="navbar-brand"><%= link_to "Home", home_index_path, :class => "link" %></p>


      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"> </li>
        </ul>
        <% if user_signed_in? %>
            <p class="navbar-text">Logged in as <strong><%= current_user.email %></strong></p>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Places", places_path %></li>
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <%= flash[:alert] %>
          <%= flash[:notice] %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/places/_form.html.erb
<%= render "layouts/errors", :object => @place %>

<div>
  <%= form_for [@place], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control"   %>
  </div>

  <div class="form-group">
    <%= f.label :street_address %>
    <%= f.text_field :street_address, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, :class => "form-control" %>
  </div>

    <%= f.submit :class=> "btn btn-default generic" %>
  <% end %>
</div>

app/views/places/create.js.erb
$('form').remove();
$('#new_place_link').show();
$('ul p').remove();
$('#places').append('<li><%= link_to place.name, place_path(place) %></li>')

app/views/places/edit.html.erb
<h1>Edit Place</h1>

<%= render "form" %>

app/views/places/edit.js.erb
$('#edit_place_link')
  .hide()
  .after('<%= j render "form" %>');

app/views/places/index.html.erb
<h1>Places</h1>

<ul id="places">
  <% @places.each do |place| %>
    <li><%= link_to place.name, place_path(place), :class => "list-link" %></li>
  <% end %>
</ul>

<p>
  <%= link_to "Add place", new_place_path, id: "new_place_link", :class=> "btn btn-default special", remote: true %>
</p>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

app/views/places/new.js.erb
$('#new_place_link')
  .hide()
  .after('<%= j render "form" %>');

app/views/places/show.html.erb
<div id= "place_name">
  <h1><%= @place.name %></h1>
</div>

<% if @place.routes.any? %>

<ul id="routes">
  <% @place.routes.each do |route| %>
  <li>
    <%= route.kind %> |
    <%= route.grade %> |
    <%= link_to "View Route", place_route_path(@place, route), :class => "list-link" %>
  </li>
  <% end %>
</ul>
<% end %>

<p><%= link_to "Add a Route", new_place_route_path(@place), id: "new_place_route_link", :class=> "btn btn-default special", remote: true %></p>
<p><%= link_to "Edit Place", edit_place_path(@place), id: "edit_place_link", :class=> "btn btn-default generic", remote: true %></p>
<p><%= link_to "Delete Place", place_path(@place),
                        :data => {:confirm => "Are you sure?",
                                  :method => "delete"}, :class=> "btn btn-default delete" %></p>

app/views/places/update.js.erb
$('form').remove();
$('#edit_place_link').show();
$('ul p').remove();
$('#place_name').append('<h1><%= @place.name %></h1>')

app/views/routes/_form.html.erb
<%= render "layouts/errors", :object => @place %>

<%= form_for [@place, @route], remote: true do |f| %>

  <div class="form-group">
    <%= f.label :kind %>
    <%= f.text_field :kind, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :grade %>
    <%= f.text_area :grade, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :class=> "btn btn-default generic" %>
  </div>
<% end  %>

app/views/routes/create.js.erb
$('form').remove();
$('#new_place_route_link').show();
$('ul p').remove();
$('#routes').append('<li><%= route.kind %> | <%= route.grade %> | <%= link_to "View Route", place_route_path(@place, route) %></li>')

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

app/views/routes/edit.js.erb
$('#edit_place_route_link')
  .hide()
  .after('<%= j render "form" %>');

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

app/views/routes/new.js.erb
$('#new_place_route_link')
  .hide()
  .after('<%= j render "form" %>');

app/views/routes/show.html.erb
<div id="route_info">
  <p>
    <strong>Type of Climbing:</strong>
    <%= @route.kind %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= @route.grade %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= @route.place.name %>
  </p>
</div>

<%= link_to 'Edit', edit_place_route_path(@route), id: "edit_place_route_link", :class=> "btn btn-default generic", remote: true  %> |
<%= link_to 'Delete', place_route_path(@route),:data => {:confirm => "You sure?", :method => 'delete'}, :class=> "btn btn-default delete" %>

app/views/routes/update.js.erb
$('form').remove();
$('#edit_place_route_link').show();
$('ul p').remove();
$('#route_info').append('<p><strong>Type of Climbing:</strong> <%= @route.kind %></p><p><strong>Grade:</strong> <%= @route.grade %></p><p><strong>Place:</strong> <%= @route.place.name %></p>')

app/views/weather_conditions/new.html.erb
<%= form_for @weather_condition do |f| %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.submit %>
<% end %>

app/views/weathers/index.html.erb
<h1>Weather Conditions</h1>

<ul>
  <% @weathers.each do |weather| %>
    <li><%= weather.city %>, <%= weather.state %>, <%= weather.forcast %></li>
  <% end %>
</ul>

app/views/weathers/new.html.erb
<%= form_for @weather do |f| %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.submit %>
<% end %>